import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";

export default function AddItemList() {
  const [itemName, setItemName] = useState("");
  const [category, setCategory] = useState("");
  const [quentity, setQuentity] = useState("");
  const [autoGeneratedList, setAutoGeneratedList] = useState([]);

  const navigate = useNavigate();

  useEffect(() => {
    axios
      .get("http://localhost:5173/shoppinglist/auto-generate-shopping-list")
      .then((res) => {
        setAutoGeneratedList(res.data);
      })
      .catch((err) => {
        console.error("Failed to fetch shopping list", err);
      });
  }, []);

  function sendData(e) {
    e.preventDefault();
    const newItem = {
      itemName,
      category,
      quentity,
    };

    axios
      .post("http://localhost:5173/shoppinglist/add-to-list", newItem)
      .then(() => {
        alert("Item Added");
        navigate("/");
      })
      .catch((err) => {
        alert(err);
      });
  }

  return (
    <div className="max-w-4xl mx-auto p-6">
      {/* Auto-Generated Shopping List Section */}
      <h2 className="text-2xl font-bold mb-4 text-gray-800">
        Auto-Generated Shopping List
      </h2>
      {autoGeneratedList.length > 0 ? (
        <div className="overflow-x-auto shadow rounded-lg mb-8">
          <table className="min-w-full bg-white border border-gray-200 text-sm text-left">
            <thead className="bg-gray-100 text-gray-700 font-semibold">
              <tr>
                <th className="px-4 py-2 border-b">Item Name</th>
                <th className="px-4 py-2 border-b">Category</th>
                <th className="px-4 py-2 border-b">Quantity</th>
                <th className="px-4 py-2 border-b">Reason</th>
              </tr>
            </thead>
            <tbody>
              {autoGeneratedList.map((item, index) => (
                <tr key={index} className="hover:bg-gray-50">
                  <td className="px-4 py-2 border-b">{item.itemName}</td>
                  <td className="px-4 py-2 border-b">{item.category}</td>
                  <td className="px-4 py-2 border-b">{item.quentity}</td>
                  <td className="px-4 py-2 border-b">{item.reason}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <p className="text-gray-500 mb-6">No items to display.</p>
      )}

      {/* Add New Item Form Section */}
      <h2 className="text-2xl font-bold mb-4 text-gray-800">Add New Item</h2>
      <form onSubmit={sendData} className="space-y-4 bg-white p-6 rounded-lg shadow">
        <div>
          <label htmlFor="itemName" className="block text-gray-700 font-medium mb-1">
            Item Name
          </label>
          <input
            type="text"
            id="itemName"
            className="w-full border border-gray-300 rounded-md p-2 focus:outline-none focus:ring focus:ring-blue-200"
            onChange={(e) => setItemName(e.target.value)}
            required
          />
        </div>

        <div>
          <label htmlFor="category" className="block text-gray-700 font-medium mb-1">
            Category
          </label>
          <input
            type="text"
            id="category"
            className="w-full border border-gray-300 rounded-md p-2 focus:outline-none focus:ring focus:ring-blue-200"
            onChange={(e) => setCategory(e.target.value)}
            required
          />
        </div>

        <div>
          <label htmlFor="quentity" className="block text-gray-700 font-medium mb-1">
            Quantity
          </label>
          <input
            type="number"
            id="quentity"
            className="w-full border border-gray-300 rounded-md p-2 focus:outline-none focus:ring focus:ring-blue-200"
            onChange={(e) => setQuentity(e.target.value)}
            required
          />
        </div>

        <button
          type="submit"
          className="bg-blue-600 text-white px-6 py-2 rounded-md hover:bg-blue-700 transition"
        >
          Add
        </button>
      </form>
    </div>
  );
}
