import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";

export default function AddItemList() {
  const [itemName, setItemName] = useState("");
  const [category, setCategory] = useState("");
  const [quentity, setQuentity] = useState("");
  const [autoGeneratedList, setAutoGeneratedList] = useState([]); // ⭐ for auto-generated shopping list

  const navigate = useNavigate();

  useEffect(() => {
    // Fetch auto-generated shopping list when page loads
    axios.get("http://localhost:9080/shoppinglist/auto-generate-shopping-list")
      .then((res) => {
        setAutoGeneratedList(res.data);
      })
      .catch((err) => {
        console.error("Failed to fetch shopping list", err);
      });
  }, []);

  function sendData(e) {
    e.preventDefault();
    const newItem = {
      itemName,
      category,
      quentity
    };

    axios.post("http://localhost:9080/shoppinglist/add-to-list", newItem)
      .then(() => {
        alert("Item Added");
        navigate('/');
      })
      .catch((err) => {
        alert(err);
      });
  }

  return (
    <div className="container mt-4">
      {/* Auto-Generated Shopping List Section */}
      <h2 className="mb-4">Auto-Generated Shopping List</h2>
      {autoGeneratedList.length > 0 ? (
        <table className="table table-bordered table-striped mb-5">
          <thead className="thead-dark">
            <tr>
              <th>Item Name</th>
              <th>Category</th>
              <th>Quantity</th>
              <th>Reason</th>
            </tr>
          </thead>
          <tbody>
            {autoGeneratedList.map((item, index) => (
              <tr key={index}>
                <td>{item.itemName}</td>
                <td>{item.category}</td>
                <td>{item.quentity}</td>
                <td>{item.reason}</td>
              </tr>
            ))}
          </tbody>
        </table>
      ) : (
        <p>No items to display.</p>
      )}

      {/* Add New Item Form Section */}
      <h2 className="mb-4">Add New Item</h2>
      <form onSubmit={sendData}>
        <div className="mb-3">
          <label htmlFor="itemName" className="form-label">Item Name</label>
          <input
            type="text"
            className="form-control"
            id="itemName"
            onChange={(e) => setItemName(e.target.value)}
            required
          />
        </div>

        <div className="mb-3">
          <label htmlFor="category" className="form-label">Category</label>
          <input
            type="text"
            className="form-control"
            id="category"
            onChange={(e) => setCategory(e.target.value)}
            required
          />
        </div>

        <div className="mb-3">
          <label htmlFor="quentity" className="form-label">Quantity</label>
          <input
            type="number"
            className="form-control"
            id="quentity"
            onChange={(e) => setQuentity(e.target.value)}
            required
          />
        </div>

        <button type="submit" className="btn btn-primary">Add</button>
      </form>
    </div>
  );
}
