import React, { useState, useEffect, useRef } from "react";
import { Link } from 'react-router-dom';
import { useNavigate } from "react-router-dom";
import { useReactToPrint } from "react-to-print";
import axios from "axios";

export default function ShoppingList() {
    const [shoppinglist, setShoppingList] = useState([]);
    const [autoGeneratedList, setAutoGeneratedList] = useState([]);
    const [searchQuery, setSearchQuery] = useState("");
    const [noResults, setNoResults] = useState(false);

    const navigate = useNavigate();
    const ComponentsRef = useRef();

   
    const getList = () => {
        axios.get("http://localhost:9080/shoppinglist/")
            .then((res) => {
                setShoppingList(res.data);
            })
            .catch((err) => {
                alert("Error fetching shopping list: " + err.message);
            });
    };

    useEffect(() => {
        // Fetch auto-generated shopping list
        function getAutoGeneratedList() {
            axios.get("http://localhost:9080/shoppinglist/auto-generate-shopping-list")
                .then((res) => {
                    setAutoGeneratedList(res.data);
                })
                .catch((err) => {
                    alert("Error fetching auto-generated shopping list: " + err.message);
                });
        }

        getAutoGeneratedList();
        getList();
    }, []);

   

    const deleteItem = (id) => {
        axios.delete(`http://localhost:9080/shoppinglist/delete/${id}`)
            .then(() => {
                alert('Item Deleted Successfully');
                setShoppingList(shoppinglist.filter(item => item._id !== id));
            })
            .catch(error => {
                console.error('There was an error!', error);
            });
    };

    const handleSearch = () => {
        if (!searchQuery.trim()) {
            getList();
            setNoResults(false);
            return;
        }

        const filteredItem = shoppinglist.filter(item =>
            Object.values(item).some(value =>
                value && value.toString().toLowerCase().includes(searchQuery.toLowerCase())
            )
        );

        if (filteredItem.length === 0) {
            setNoResults(true);
        } else {
            setNoResults(false);
            setShoppingList(filteredItem);
        }
    };

    return (
        <div className="container mt-5">
            <h1 className="text-center mb-4">Shopping List</h1>

            {/* Search bar */}
            <div className="mb-4 text-center">
                <input
                    onChange={(e) => setSearchQuery(e.target.value)}
                    type="text"
                    name="search"
                    placeholder="Search"
                    style={{
                        padding: "8px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                        width: "200px"
                    }}
                />
                <button
                    onClick={handleSearch}
                    style={{
                        backgroundColor: "blue",
                        color: "white",
                        border: "none",
                        padding: "8px 15px",
                        borderRadius: "5px",
                        marginLeft: "10px",
                        cursor: "pointer"
                    }}
                >
                    Search
                </button>
            </div>

            {/* Search result message */}
            {noResults ? (
                <div>
                    <p>No Details</p>
                </div>
            ) : (
                <div>

                    {/* Main shopping list */}
                    <h2>All Shopping Items</h2>
                    <table className="table table-striped table-hover">
                        <thead className="thead-dark">
                            <tr>
                                <th>Item Name</th>
                                <th>Category</th>
                                <th>Quantity</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {shoppinglist.map((item, index) => (
                                <tr key={index}>
                                    <td>{item.itemName}</td>
                                    <td>{item.category}</td>
                                    <td>{item.quentity}</td>
                                    <td>
                                        <Link to={`/update/${item._id}`} className="btn btn-info btn-sm">
                                            Edit
                                        </Link>
                                    </td>
                                    <td>
                                        <button
                                            type="button"
                                            className="btn btn-danger btn-sm"
                                            onClick={() => deleteItem(item._id)}
                                        >
                                            Delete
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>

                    {/* Auto-generated shopping list */}
                    <div className="mb-4">
                        <h2>Auto-Generated Shopping List</h2>
                        <table className="table table-striped table-hover">
                            <thead className="thead-dark">
                                <tr>
                                    <th>Item Name</th>
                                    <th>Category</th>
                                    <th>Quantity</th>
                                    <th>Reason</th>
                                </tr>
                            </thead>
                            <tbody>
                                {autoGeneratedList.length > 0 ? (
                                    autoGeneratedList.map((item, index) => (
                                        <tr key={index}>
                                            <td>{item.itemName}</td>
                                            <td>{item.category}</td>
                                            <td>{item.quentity}</td>
                                            <td>{item.reason}</td>
                                        </tr>
                                    ))
                                ) : (
                                    <tr>
                                        <td colSpan="4">No auto-generated items found.</td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}

            {/* Action buttons */}
            <div className="text-center mt-4">
                <Link to="/addItem" className="btn btn-primary">
                    Add New Item
                </Link>
                <Link to={`/list`} className="btn btn-info ml-2">
                    Report
                </Link>
            </div>
        </div>
    );
}
