import React, { useState, useEffect, useRef } from "react";
import { Link } from 'react-router-dom';
import { useNavigate } from "react-router-dom";
import { useReactToPrint } from "react-to-print";
import axios from "axios";

export default function ShoppingList() {
    const [shoppinglist, setShoppingList] = useState([]);
    const [autoGeneratedList, setAutoGeneratedList] = useState([]); // State to hold auto-generated shopping list

    useEffect(() => {
        // Fetch the auto-generated shopping list
        function getAutoGeneratedList() {
            axios.get("http://localhost:9080/shoppinglist/auto-generate-shopping-list")
                .then((res) => {
                    setAutoGeneratedList(res.data); // Set auto-generated list
                })
                .catch((err) => {
                    alert("Error fetching auto-generated shopping list: " + err.message);
                });
        }

        getAutoGeneratedList();

        // Fetch the main shopping list
        function getList() {
            axios.get("http://localhost:9080/shoppinglist/")
                .then((res) => {
                    setShoppingList(res.data); // Set main shopping list
                })
                .catch((err) => {
                    alert("Error fetching shopping list: " + err.message);
                });
        }

        getList();
    }, []);

    const ComponentsRef = useRef();
    const handlePrint = useReactToPrint({
        content: () => ComponentsRef.current,
        documentTitle: "Shopping List",
        onAfterPrint: () => alert("Report Downloaded!"),
    });

    const navigate = useNavigate();

    const deleteItem = (id) => {
        axios.delete(`http://localhost:9080/shoppinglist/delete/${id}`)
            .then(() => {
                alert('Item Deleted Successfully');
                navigate('/');
                setShoppingList(shoppinglist.filter(shoppinglist => shoppinglist._id !== id));
            })
            .catch(error => {
                console.error('There was an error!', error);
            });
    };

    return (
        <div className="container mt-5">
            <h1 className="text-center mb-4">Shopping List</h1>

            {/* Auto-generated shopping list section */}
            <div className="mb-4">
                <h2>Auto-Generated Shopping List</h2>
                <table className="table table-striped table-hover">
                    <thead className="thead-dark">
                        <tr>
                            <th>Item Name</th>
                            <th>Category</th>
                            <th>Quantity</th>
                            <th>Reason</th>
                        </tr>
                    </thead>
                    <tbody>
                        {autoGeneratedList.length > 0 ? (
                            autoGeneratedList.map((item, index) => (
                                <tr key={index}>
                                    <td>{item.itemName}</td>
                                    <td>{item.category}</td>
                                    <td>{item.quentity}</td>
                                    <td>{item.reason}</td>
                                </tr>
                            ))
                        ) : (
                            <tr>
                                <td colSpan="4">No auto-generated items found.</td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>

            {/* Main shopping list section */}
            <h2>All Shopping Items</h2>
            <table className="table table-striped table-hover">
                <thead className="thead-dark">
                    <tr>
                        <th>Item Name</th>
                        <th>Category</th>
                        <th>Quantity</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {shoppinglist.map((item, index) => (
                        <tr key={index}>
                            <td>{item.itemName}</td>
                            <td>{item.category}</td>
                            <td>{item.quentity}</td>
                            <td>
                                <Link to={`/update/${item._id}`} className="btn btn-info btn-sm">
                                    Edit
                                </Link>
                            </td>
                            <td>
                                <button
                                    type="button"
                                    className="btn btn-danger btn-sm"
                                    onClick={() => deleteItem(item._id)}
                                >
                                    Delete
                                </button>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>

            {/* Buttons for adding items or generating reports */}
            <div className="text-center mt-4">
                <Link to="/addItem" className="btn btn-primary">
                    Add New Item
                </Link>

                <Link to={`/list`} className="btn btn-info">Report</Link>
            </div>
        </div>
    );
}
